spring.datasource.url=jdbc:postgresql://localhost:5432/smalltransaction_demo
spring.datasource.username=postgres
spring.datasource.password=Texas@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8083